export type AppMode =
    | 'menu'
    | 'slime-mold'
    | 'gray-scott'
    | 'particle-life'
    | 'flow'
    | 'pellets'
    | 'gradient-editor'
    | 'voronoi-ca'
    | 'moire'
    | 'primordial-particles'
    | 'vectors'
    | 'gradient'
    | 'how-to-play'
    | 'settings';
